#spring.application.name=CampusThreads

spring:
  config:
    import: "env.properties"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL8Dialect
    show-sql: true
#  mail:
#    host: smtp.titan.email
#    port: 587
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    protocol: smtp

jwt:
  expiration:
    time: 900000
  public:
    key: classpath:public.key
  private:
    key: classpath:jwtprivate.key

